language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: PepijnBoers
  password:
    secure: J1Bu5VDOas6dNjNINqa1H8/yTEl0tGj3PSe5w4oTqiogGdm+1FNALIUb73UXDo4m0+4Yiz9gur3QkZAf1a0/UfKMB19dvVQhfhzuaRJh3LrvwIaIwfA3UgDgsRL/dwxb+P/YbEcSAIKbVdbTsLFX0XL8GkUwXqJRfXAz966Lfky2zdrvFU+mpDPsTb+rIcmsIbVpm5pCaZToJkj1euDkK5Bq7GO6qiBDjBakwzp2Bh0qM72lskKqwHc0wSdDXzN6jMp9QBAyruOoiU+WhXb04KHEUA2wBownAVq+OtFNAKAyIRhM14hQiYWRTKcqp71mBVlOZZXWy5o0d9eoaS4ExuBGu7zC8d2ruAvQZCeS4o1XwcawfoyABGNTw3BlvvA+kfrBs7Bp5YyliqRj571BMyNZlFRldns38VoBWzPDhBIYrb3o1rFBKIgPIJQfBrVaAPHH4EvdFp+OzsppWdVHK2bSsuwUUakSzCNVG5lkQWZ+4USYXzeA5bNDr/5KWJznTyFRooQ1ICqFHO8zpG62gYlrCzLM5j3V95/x0yuHWna8L40wu18UM1/qS3E41B4YtYJ1VE4obEiV1raKK5zsVT2uWxegXCrbDUYpT4cGxjn7/tE+QzUhTf0CqCaxoP4qoLGrbDqhbn6OtX39QkCmmPsrDb5d4nkLHfHM97NcC4I=
  on:
    tags: true
    repo: PepijnBoers/prijsoog
    python: 3.8
